kind: ReplicationController
apiVersion: v1
metadata:
  name: spark-worker-controller-kmeans
spec:
  replicas: 1
  selector:
    component: spark-worker-kmeans
  template:
    metadata:
      labels:
        component: spark-worker-kmeans
    spec:
      containers:
        - name: spark-worker
          image: myregistry.local:5000/spark:2.4.3
          volumeMounts:
            - name: kmeans
              mountPath: /tmp/kmeans
          #command: ["/bin/sh", "-ec", "while :; do echo '.'; sleep 5 ; done"]
          command: ["/tmp/kmeans/start-worker.sh"]
          ports:
            - containerPort: 7077
            - containerPort: 8080
          resources:
            limits:
               memory: "2048Mi"
               cpu: "1000m"
      nodeSelector:
        diskspeed: thinkstation-e32
      volumes:
        - name: kmeans
          hostPath:
            path: /home/zcp/spark_benchmark_kubernetes/kmeans
